buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.0.0'
    }
}

plugins {
    id 'lifecycle-base'
    id 'io.github.gradle-nexus.publish-plugin' version '2.0.0'
}

apply plugin: 'io.github.gradle-nexus.publish-plugin'

nexusPublishing {
    repositories {
        sonatype {
            stagingProfileId.set(MAVEN_GROUP_ID)
            nexusUrl.set(uri('https://ossrh-staging-api.central.sonatype.com/service/local/'))
            username.set(System.getenv("MAVEN_USERNAME"))
            password.set(System.getenv("MAVEN_PASSWORD"))
        }
    }
}

allprojects {
    group = 'com.auth0.android'

    repositories {
        google()
        mavenCentral()
    }
}

tasks.named("clean").configure {
    delete 'CHANGELOG.md.release'
}
