buildscript {
    repositories {
        google()
        mavenCentral()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.6.1'
    }
}

plugins {
    id 'lifecycle-base'
}

allprojects {
    group = 'com.auth0.android'

    repositories {
        google()
        mavenCentral()
        jcenter()
    }
}

tasks.named("clean").configure {
    delete 'CHANGELOG.md.release'
}
