# Project-wide Gradle settings.

# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE *will override*
# any settings specified in this file.

# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html

# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
org.gradle.jvmargs=-Xmx1536m

# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. More details, visit
# http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:decoupled_projects
# org.gradle.parallel=true

android.useAndroidX=true

# Maven publishing / POM metadata
GROUP=com.auth0.android
# Sonatype staging profile namespace (parent profile covering all com.auth0.* artifacts)
MAVEN_GROUP_ID=com.auth0
POM_ARTIFACT_ID=jwtdecode

POM_NAME=JWTDecode.Android
POM_DESCRIPTION=JWT Decoding library for Android
POM_PACKAGING=aar

POM_URL=https://github.com/auth0/JWTDecode.Android
POM_SCM_URL=https://github.com/auth0/JWTDecode.Android
POM_SCM_CONNECTION=scm:git@github.com:auth0/JWTDecode.Android.git
POM_SCM_DEV_CONNECTION=scm:git@github.com:auth0/JWTDecode.Android.git

POM_LICENCE_NAME=The MIT License (MIT)
POM_LICENCE_URL=https://spdx.org/licenses/MIT.html
POM_LICENCE_DIST=repo

POM_DEVELOPER_ID=auth0
POM_DEVELOPER_NAME=Auth0
POM_DEVELOPER_EMAIL=oss@auth0.com