plugins {
    id 'com.android.library'
}

apply from: rootProject.file('gradle/versioning.gradle')

version = getVersionFromFile()

logger.lifecycle("Using version ${version} for ${name}")

android {
    compileSdkVersion 29

    defaultConfig {
        minSdkVersion 15
        targetSdkVersion 29
        versionCode 1
        versionName project.version
    }
}

dependencies {
    implementation 'androidx.annotation:annotation:1.1.0'
    implementation 'com.google.code.gson:gson:2.8.9'

    testImplementation 'junit:junit:4.13'
    testImplementation 'org.hamcrest:java-hamcrest:2.0.0.0'
    testImplementation('org.robolectric:robolectric:4.3.1') {
        // https://github.com/robolectric/robolectric/issues/5245
        exclude group: 'com.google.auto.service', module: 'auto-service'
    }
    testImplementation 'org.mockito:mockito-core:3.2.4'
}

apply from: rootProject.file('gradle/jacoco.gradle')
apply from: rootProject.file('gradle/maven-publish.gradle')
