name: Publish Release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: The branch to release from.
        required: true
        default: master

permissions:
  contents: read

jobs:
  publish:
    name: Publish to Maven Central
    runs-on: ubuntu-latest
    environment: release

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.branch }}

      - uses: ./.github/actions/setup

      - run: ./gradlew clean assemble -PisSnapshot=false

      - run: ./gradlew exportVersion -PisSnapshot=false

      - env:
          OSSR_USERNAME: ${{ secrets.OSSR_USERNAME }}
          OSSR_PASSWORD: ${{ secrets.OSSR_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        run: ./gradlew publishAndroidLibraryPublicationToMavenRepository -PossrhUsername="$OSSR_USERNAME" -PossrhPassword="$OSSR_PASSWORD" -PsigningKey="$SIGNING_KEY" -PsigningPassword="$SIGNING_PASSWORD" -PisSnapshot=false
