name: Build and Test

on:
  merge_group:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

env:
  GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"
  _JAVA_OPTIONS: -Xms512m -Xmx1024m

jobs:
  unit:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - run: ./gradlew clean test jacocoTestReport --console=plain

      - uses: codecov/codecov-action@ab904c41d6ece82784817410c45d8b8c02684457 # pin@3.1.6
